/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\document\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-cd548110",
    path: "/CRM/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd548110").then(next)
    },
  },
  {
    path: "/CRM/index.html",
    redirect: "/CRM/"
  },
  {
    name: "v-54d0e31c",
    path: "/CRM/code/qianduan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54d0e31c").then(next)
    },
  },
  {
    name: "v-4dfad978",
    path: "/CRM/publish/operation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dfad978").then(next)
    },
  },
  {
    name: "v-9792295c",
    path: "/CRM/code/houtai.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9792295c").then(next)
    },
  },
  {
    name: "v-289e9d30",
    path: "/MySql/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-289e9d30").then(next)
    },
  },
  {
    path: "/MySql/index.html",
    redirect: "/MySql/"
  },
  {
    name: "v-64abc2e2",
    path: "/DNS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64abc2e2").then(next)
    },
  },
  {
    path: "/DNS/index.html",
    redirect: "/DNS/"
  },
  {
    name: "v-16f7f469",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16f7f469").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7a063102",
    path: "/en/CRM/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a063102").then(next)
    },
  },
  {
    path: "/en/CRM/index.html",
    redirect: "/en/CRM/"
  },
  {
    name: "v-71c916ce",
    path: "/en/CRM/code/houtai.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71c916ce").then(next)
    },
  },
  {
    name: "v-854bc2a2",
    path: "/en/CRM/code/qianduan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-854bc2a2").then(next)
    },
  },
  {
    name: "v-030d341f",
    path: "/en/DNS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-030d341f").then(next)
    },
  },
  {
    path: "/en/DNS/index.html",
    redirect: "/en/DNS/"
  },
  {
    name: "v-81963628",
    path: "/en/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81963628").then(next)
    },
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-687618b6",
    path: "/en/CRM/publish/operation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-687618b6").then(next)
    },
  },
  {
    name: "v-7594c202",
    path: "/en/MySql/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7594c202").then(next)
    },
  },
  {
    path: "/en/MySql/index.html",
    redirect: "/en/MySql/"
  },
  {
    name: "v-034ba7bb",
    path: "/en/features/components/avatar-upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-034ba7bb").then(next)
    },
  },
  {
    name: "v-08345ddf",
    path: "/en/features/components/breadcrumb.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08345ddf").then(next)
    },
  },
  {
    name: "v-536b2453",
    path: "/en/features/components/back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-536b2453").then(next)
    },
  },
  {
    name: "v-3f6978df",
    path: "/en/features/components/draggable-kanban.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f6978df").then(next)
    },
  },
  {
    name: "v-f23ba6c2",
    path: "/en/features/components/charts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f23ba6c2").then(next)
    },
  },
  {
    name: "v-d3ee5542",
    path: "/en/features/components/draggable-menu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d3ee5542").then(next)
    },
  },
  {
    name: "v-dfc66402",
    path: "/en/features/components/draggable-select.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dfc66402").then(next)
    },
  },
  {
    name: "v-600b2e7f",
    path: "/en/features/components/draggable-list.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-600b2e7f").then(next)
    },
  },
  {
    name: "v-10c8515f",
    path: "/en/features/components/dropzone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10c8515f").then(next)
    },
  },
  {
    name: "v-c7e351b2",
    path: "/en/features/components/error-log.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7e351b2").then(next)
    },
  },
  {
    name: "v-2aa55127",
    path: "/en/features/components/github-corner.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2aa55127").then(next)
    },
  },
  {
    name: "v-a1b226da",
    path: "/en/features/components/hamburger.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a1b226da").then(next)
    },
  },
  {
    name: "v-5adb0e95",
    path: "/en/features/components/header-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5adb0e95").then(next)
    },
  },
  {
    name: "v-757c622f",
    path: "/en/features/components/lang-select.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-757c622f").then(next)
    },
  },
  {
    name: "v-3095707e",
    path: "/en/features/components/json-editor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3095707e").then(next)
    },
  },
  {
    name: "v-1bfcb08f",
    path: "/en/features/components/markdown-editor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bfcb08f").then(next)
    },
  },
  {
    name: "v-553ce6ae",
    path: "/en/features/components/rich-editor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-553ce6ae").then(next)
    },
  },
  {
    name: "v-722c177f",
    path: "/en/features/components/pagination.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-722c177f").then(next)
    },
  },
  {
    name: "v-7f980fbf",
    path: "/en/features/components/material-input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f980fbf").then(next)
    },
  },
  {
    name: "v-7b618219",
    path: "/en/features/components/pan-thumb.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b618219").then(next)
    },
  },
  {
    name: "v-1c4802df",
    path: "/en/features/components/screenfull.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c4802df").then(next)
    },
  },
  {
    name: "v-2046a77f",
    path: "/en/features/components/right-panel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2046a77f").then(next)
    },
  },
  {
    name: "v-2f49a1d6",
    path: "/en/features/components/size-select.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f49a1d6").then(next)
    },
  },
  {
    name: "v-d7668bc2",
    path: "/en/features/components/sticky.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7668bc2").then(next)
    },
  },
  {
    name: "v-6aa3b1a1",
    path: "/en/features/components/text-hover-effect.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6aa3b1a1").then(next)
    },
  },
  {
    name: "v-09c4183f",
    path: "/en/features/components/theme-picker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09c4183f").then(next)
    },
  },
  {
    name: "v-7d8d5342",
    path: "/en/features/components/upload-excel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d8d5342").then(next)
    },
  },
  {
    name: "v-77bedc46",
    path: "/en/features/directives/clipboard.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77bedc46").then(next)
    },
  },
  {
    name: "v-dce51242",
    path: "/en/features/components/upload-image.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dce51242").then(next)
    },
  },
  {
    name: "v-7dae1cbf",
    path: "/en/features/directives/draggable-dialog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7dae1cbf").then(next)
    },
  },
  {
    name: "v-c45a09c2",
    path: "/en/features/directives/permission.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c45a09c2").then(next)
    },
  },
  {
    name: "v-71a63fc6",
    path: "/en/npm&yarn/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71a63fc6").then(next)
    },
  },
  {
    path: "/en/npm&yarn/index.html",
    redirect: "/en/npm&yarn/"
  },
  {
    name: "v-6e5df525",
    path: "/en/features/icons/svg-icons.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e5df525").then(next)
    },
  },
  {
    name: "v-0df11b55",
    path: "/en/features/directives/waves.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0df11b55").then(next)
    },
  },
  {
    name: "v-15072225",
    path: "/en/features/pwa/service-worker-update-popup.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15072225").then(next)
    },
  },
  {
    name: "v-37db5682",
    path: "/en/powerplatform/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37db5682").then(next)
    },
  },
  {
    path: "/en/powerplatform/index.html",
    redirect: "/en/powerplatform/"
  },
  {
    name: "v-5b522dd9",
    path: "/en/powerplatform/powerapps/view.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b522dd9").then(next)
    },
  },
  {
    name: "v-733c12d9",
    path: "/en/powerplatform/powerapps/code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-733c12d9").then(next)
    },
  },
  {
    name: "v-9ae58c02",
    path: "/en/nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9ae58c02").then(next)
    },
  },
  {
    path: "/en/nginx/index.html",
    redirect: "/en/nginx/"
  },
  {
    name: "v-f9e97bc0",
    path: "/en/nginx/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9e97bc0").then(next)
    },
  },
  {
    path: "/en/nginx/config/index.html",
    redirect: "/en/nginx/config/"
  },
  {
    name: "v-c7d6cf9c",
    path: "/features/components/avatar-upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7d6cf9c").then(next)
    },
  },
  {
    name: "v-0c7dbb9c",
    path: "/features/components/back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c7dbb9c").then(next)
    },
  },
  {
    name: "v-b7d0266c",
    path: "/features/components/breadcrumb.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b7d0266c").then(next)
    },
  },
  {
    name: "v-9b0e17b4",
    path: "/features/components/charts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b0e17b4").then(next)
    },
  },
  {
    name: "v-9b6e443c",
    path: "/features/components/draggable-kanban.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b6e443c").then(next)
    },
  },
  {
    name: "v-769cbb14",
    path: "/features/components/draggable-list.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-769cbb14").then(next)
    },
  },
  {
    name: "v-9c1298dc",
    path: "/features/components/draggable-menu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c1298dc").then(next)
    },
  },
  {
    name: "v-fa737cd0",
    path: "/features/components/draggable-select.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa737cd0").then(next)
    },
  },
  {
    name: "v-f45c38cc",
    path: "/features/components/dropzone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f45c38cc").then(next)
    },
  },
  {
    name: "v-2faa5c1c",
    path: "/features/components/github-corner.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2faa5c1c").then(next)
    },
  },
  {
    name: "v-396331f2",
    path: "/features/components/error-log.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-396331f2").then(next)
    },
  },
  {
    name: "v-6f0610b2",
    path: "/features/components/hamburger.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f0610b2").then(next)
    },
  },
  {
    name: "v-33d27852",
    path: "/features/components/header-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33d27852").then(next)
    },
  },
  {
    name: "v-4c6a8ad2",
    path: "/features/components/json-editor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c6a8ad2").then(next)
    },
  },
  {
    name: "v-2537791c",
    path: "/features/components/lang-select.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2537791c").then(next)
    },
  },
  {
    name: "v-75154f72",
    path: "/features/components/markdown-editor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75154f72").then(next)
    },
  },
  {
    name: "v-222a2188",
    path: "/features/components/material-input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-222a2188").then(next)
    },
  },
  {
    name: "v-582b381c",
    path: "/features/components/pagination.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-582b381c").then(next)
    },
  },
  {
    name: "v-790de5dc",
    path: "/features/components/pan-thumb.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-790de5dc").then(next)
    },
  },
  {
    name: "v-dc84bb1c",
    path: "/features/components/right-panel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc84bb1c").then(next)
    },
  },
  {
    name: "v-0115b35c",
    path: "/features/components/rich-editor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0115b35c").then(next)
    },
  },
  {
    name: "v-20b3e6da",
    path: "/features/components/screenfull.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20b3e6da").then(next)
    },
  },
  {
    name: "v-e4d5fadc",
    path: "/features/components/size-select.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4d5fadc").then(next)
    },
  },
  {
    name: "v-44c909ec",
    path: "/features/components/theme-picker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44c909ec").then(next)
    },
  },
  {
    name: "v-ab08a604",
    path: "/features/components/sticky.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ab08a604").then(next)
    },
  },
  {
    name: "v-3b819adc",
    path: "/features/components/text-hover-effect.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b819adc").then(next)
    },
  },
  {
    name: "v-6b67f80c",
    path: "/features/components/upload-excel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b67f80c").then(next)
    },
  },
  {
    name: "v-1c74a5b2",
    path: "/features/components/upload-image.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c74a5b2").then(next)
    },
  },
  {
    name: "v-214876dc",
    path: "/features/directives/draggable-dialog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-214876dc").then(next)
    },
  },
  {
    name: "v-1798bd5c",
    path: "/features/directives/clipboard.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1798bd5c").then(next)
    },
  },
  {
    name: "v-e78344e4",
    path: "/features/directives/permission.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e78344e4").then(next)
    },
  },
  {
    name: "v-af4635f8",
    path: "/features/icons/svg-icons.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af4635f8").then(next)
    },
  },
  {
    name: "v-25d06128",
    path: "/npm&yarn/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25d06128").then(next)
    },
  },
  {
    path: "/npm&yarn/index.html",
    redirect: "/npm&yarn/"
  },
  {
    name: "v-16454b68",
    path: "/features/pwa/service-worker-update-popup.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16454b68").then(next)
    },
  },
  {
    name: "v-b24faef8",
    path: "/powerplatform/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b24faef8").then(next)
    },
  },
  {
    path: "/powerplatform/index.html",
    redirect: "/powerplatform/"
  },
  {
    name: "v-1f73df28",
    path: "/powerplatform/powerapps/code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f73df28").then(next)
    },
  },
  {
    name: "v-45589d52",
    path: "/features/directives/waves.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45589d52").then(next)
    },
  },
  {
    name: "v-489f8608",
    path: "/powerplatform/powerapps/view.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-489f8608").then(next)
    },
  },
  {
    name: "v-eb92f680",
    path: "/nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eb92f680").then(next)
    },
  },
  {
    path: "/nginx/index.html",
    redirect: "/nginx/"
  },
  {
    name: "v-b38ec94e",
    path: "/nginx/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b38ec94e").then(next)
    },
  },
  {
    path: "/nginx/config/index.html",
    redirect: "/nginx/config/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]