/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "文档",
  "description": "文档描述",
  "base": "/",
  "pages": [
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/CRM/",
      "relativePath": "CRM/README.md",
      "key": "v-cd548110",
      "path": "/CRM/"
    },
    {
      "title": "code",
      "frontmatter": {},
      "regularPath": "/CRM/code/qianduan.html",
      "relativePath": "CRM/code/qianduan.md",
      "key": "v-54d0e31c",
      "path": "/CRM/code/qianduan.html"
    },
    {
      "title": "Dynamics 365",
      "frontmatter": {},
      "regularPath": "/CRM/publish/operation.html",
      "relativePath": "CRM/publish/operation.md",
      "key": "v-4dfad978",
      "path": "/CRM/publish/operation.html",
      "headers": [
        {
          "level": 2,
          "title": "导出窗体",
          "slug": "导出窗体"
        },
        {
          "level": 2,
          "title": "导出代码",
          "slug": "导出代码"
        },
        {
          "level": 2,
          "title": "导入解决方案",
          "slug": "导入解决方案"
        }
      ]
    },
    {
      "title": "代码",
      "frontmatter": {},
      "regularPath": "/CRM/code/houtai.html",
      "relativePath": "CRM/code/houtai.md",
      "key": "v-9792295c",
      "path": "/CRM/code/houtai.html",
      "headers": [
        {
          "level": 2,
          "title": "给和",
          "slug": "给和"
        }
      ]
    },
    {
      "title": "语句",
      "frontmatter": {},
      "regularPath": "/MySql/",
      "relativePath": "MySql/README.md",
      "key": "v-289e9d30",
      "path": "/MySql/"
    },
    {
      "frontmatter": {},
      "regularPath": "/DNS/",
      "relativePath": "DNS/README.md",
      "key": "v-64abc2e2",
      "path": "/DNS/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "images/hero.png",
        "features": [
          {
            "title": "国际化",
            "details": "内建业界通用的国际化方案"
          },
          {
            "title": "主题",
            "details": "支持多种动态换肤功能"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2023"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-16f7f469",
      "path": "/"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/en/CRM/",
      "relativePath": "en/CRM/README.md",
      "key": "v-7a063102",
      "path": "/en/CRM/"
    },
    {
      "title": "code",
      "frontmatter": {},
      "regularPath": "/en/CRM/code/houtai.html",
      "relativePath": "en/CRM/code/houtai.md",
      "key": "v-71c916ce",
      "path": "/en/CRM/code/houtai.html"
    },
    {
      "title": "code",
      "frontmatter": {},
      "regularPath": "/en/CRM/code/qianduan.html",
      "relativePath": "en/CRM/code/qianduan.md",
      "key": "v-854bc2a2",
      "path": "/en/CRM/code/qianduan.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/DNS/",
      "relativePath": "en/DNS/README.md",
      "key": "v-030d341f",
      "path": "/en/DNS/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "../images/hero.png",
        "features": [
          {
            "title": "Globalization",
            "details": "Built-in industry universal international solution"
          },
          {
            "title": "Theming",
            "details": "Supports multiple dynamic skin methods"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2023"
      },
      "regularPath": "/en/",
      "relativePath": "en/README.md",
      "key": "v-81963628",
      "path": "/en/"
    },
    {
      "title": "Dynamics 365",
      "frontmatter": {},
      "regularPath": "/en/CRM/publish/operation.html",
      "relativePath": "en/CRM/publish/operation.md",
      "key": "v-687618b6",
      "path": "/en/CRM/publish/operation.html",
      "headers": [
        {
          "level": 2,
          "title": "导出窗体",
          "slug": "导出窗体"
        },
        {
          "level": 2,
          "title": "导出代码",
          "slug": "导出代码"
        },
        {
          "level": 2,
          "title": "导入解决方案",
          "slug": "导入解决方案"
        }
      ]
    },
    {
      "title": "语句",
      "frontmatter": {},
      "regularPath": "/en/MySql/",
      "relativePath": "en/MySql/README.md",
      "key": "v-7594c202",
      "path": "/en/MySql/"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/avatar-upload.html",
      "relativePath": "en/features/components/avatar-upload.md",
      "key": "v-034ba7bb",
      "path": "/en/features/components/avatar-upload.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/breadcrumb.html",
      "relativePath": "en/features/components/breadcrumb.md",
      "key": "v-08345ddf",
      "path": "/en/features/components/breadcrumb.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/back-to-top.html",
      "relativePath": "en/features/components/back-to-top.md",
      "key": "v-536b2453",
      "path": "/en/features/components/back-to-top.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/draggable-kanban.html",
      "relativePath": "en/features/components/draggable-kanban.md",
      "key": "v-3f6978df",
      "path": "/en/features/components/draggable-kanban.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/charts.html",
      "relativePath": "en/features/components/charts.md",
      "key": "v-f23ba6c2",
      "path": "/en/features/components/charts.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/draggable-menu.html",
      "relativePath": "en/features/components/draggable-menu.md",
      "key": "v-d3ee5542",
      "path": "/en/features/components/draggable-menu.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/draggable-select.html",
      "relativePath": "en/features/components/draggable-select.md",
      "key": "v-dfc66402",
      "path": "/en/features/components/draggable-select.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/draggable-list.html",
      "relativePath": "en/features/components/draggable-list.md",
      "key": "v-600b2e7f",
      "path": "/en/features/components/draggable-list.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/dropzone.html",
      "relativePath": "en/features/components/dropzone.md",
      "key": "v-10c8515f",
      "path": "/en/features/components/dropzone.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/error-log.html",
      "relativePath": "en/features/components/error-log.md",
      "key": "v-c7e351b2",
      "path": "/en/features/components/error-log.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/github-corner.html",
      "relativePath": "en/features/components/github-corner.md",
      "key": "v-2aa55127",
      "path": "/en/features/components/github-corner.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/hamburger.html",
      "relativePath": "en/features/components/hamburger.md",
      "key": "v-a1b226da",
      "path": "/en/features/components/hamburger.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/header-search.html",
      "relativePath": "en/features/components/header-search.md",
      "key": "v-5adb0e95",
      "path": "/en/features/components/header-search.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/lang-select.html",
      "relativePath": "en/features/components/lang-select.md",
      "key": "v-757c622f",
      "path": "/en/features/components/lang-select.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/json-editor.html",
      "relativePath": "en/features/components/json-editor.md",
      "key": "v-3095707e",
      "path": "/en/features/components/json-editor.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/markdown-editor.html",
      "relativePath": "en/features/components/markdown-editor.md",
      "key": "v-1bfcb08f",
      "path": "/en/features/components/markdown-editor.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/rich-editor.html",
      "relativePath": "en/features/components/rich-editor.md",
      "key": "v-553ce6ae",
      "path": "/en/features/components/rich-editor.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/pagination.html",
      "relativePath": "en/features/components/pagination.md",
      "key": "v-722c177f",
      "path": "/en/features/components/pagination.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/material-input.html",
      "relativePath": "en/features/components/material-input.md",
      "key": "v-7f980fbf",
      "path": "/en/features/components/material-input.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/pan-thumb.html",
      "relativePath": "en/features/components/pan-thumb.md",
      "key": "v-7b618219",
      "path": "/en/features/components/pan-thumb.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/screenfull.html",
      "relativePath": "en/features/components/screenfull.md",
      "key": "v-1c4802df",
      "path": "/en/features/components/screenfull.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/right-panel.html",
      "relativePath": "en/features/components/right-panel.md",
      "key": "v-2046a77f",
      "path": "/en/features/components/right-panel.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/size-select.html",
      "relativePath": "en/features/components/size-select.md",
      "key": "v-2f49a1d6",
      "path": "/en/features/components/size-select.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/sticky.html",
      "relativePath": "en/features/components/sticky.md",
      "key": "v-d7668bc2",
      "path": "/en/features/components/sticky.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/text-hover-effect.html",
      "relativePath": "en/features/components/text-hover-effect.md",
      "key": "v-6aa3b1a1",
      "path": "/en/features/components/text-hover-effect.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/theme-picker.html",
      "relativePath": "en/features/components/theme-picker.md",
      "key": "v-09c4183f",
      "path": "/en/features/components/theme-picker.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/upload-excel.html",
      "relativePath": "en/features/components/upload-excel.md",
      "key": "v-7d8d5342",
      "path": "/en/features/components/upload-excel.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/directives/clipboard.html",
      "relativePath": "en/features/directives/clipboard.md",
      "key": "v-77bedc46",
      "path": "/en/features/directives/clipboard.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/components/upload-image.html",
      "relativePath": "en/features/components/upload-image.md",
      "key": "v-dce51242",
      "path": "/en/features/components/upload-image.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/directives/draggable-dialog.html",
      "relativePath": "en/features/directives/draggable-dialog.md",
      "key": "v-7dae1cbf",
      "path": "/en/features/directives/draggable-dialog.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/directives/permission.html",
      "relativePath": "en/features/directives/permission.md",
      "key": "v-c45a09c2",
      "path": "/en/features/directives/permission.html"
    },
    {
      "title": "npm",
      "frontmatter": {},
      "regularPath": "/en/npm&yarn/",
      "relativePath": "en/npm&yarn/README.md",
      "key": "v-71a63fc6",
      "path": "/en/npm&yarn/",
      "headers": [
        {
          "level": 2,
          "title": "全局安装 nrm",
          "slug": "全局安装-nrm"
        },
        {
          "level": 2,
          "title": "查看当前可使用的镜像源",
          "slug": "查看当前可使用的镜像源"
        },
        {
          "level": 2,
          "title": "使用镜像源进行依赖下载",
          "slug": "使用镜像源进行依赖下载"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/icons/svg-icons.html",
      "relativePath": "en/features/icons/svg-icons.md",
      "key": "v-6e5df525",
      "path": "/en/features/icons/svg-icons.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/directives/waves.html",
      "relativePath": "en/features/directives/waves.md",
      "key": "v-0df11b55",
      "path": "/en/features/directives/waves.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/en/features/pwa/service-worker-update-popup.html",
      "relativePath": "en/features/pwa/service-worker-update-popup.md",
      "key": "v-15072225",
      "path": "/en/features/pwa/service-worker-update-popup.html"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/en/powerplatform/",
      "relativePath": "en/powerplatform/README.md",
      "key": "v-37db5682",
      "path": "/en/powerplatform/"
    },
    {
      "title": "界面操作",
      "frontmatter": {},
      "regularPath": "/en/powerplatform/powerapps/view.html",
      "relativePath": "en/powerplatform/powerapps/view.md",
      "key": "v-5b522dd9",
      "path": "/en/powerplatform/powerapps/view.html",
      "headers": [
        {
          "level": 2,
          "title": "sftp",
          "slug": "sftp"
        }
      ]
    },
    {
      "title": "PCF控件",
      "frontmatter": {},
      "regularPath": "/en/powerplatform/powerapps/code.html",
      "relativePath": "en/powerplatform/powerapps/code.md",
      "key": "v-733c12d9",
      "path": "/en/powerplatform/powerapps/code.html",
      "headers": [
        {
          "level": 2,
          "title": "创建",
          "slug": "创建"
        },
        {
          "level": 2,
          "title": "更新",
          "slug": "更新"
        }
      ]
    },
    {
      "title": "1.nginx的proxy_pass配置路径，加与不加“/”差异巨大",
      "frontmatter": {},
      "regularPath": "/en/nginx/",
      "relativePath": "en/nginx/README.md",
      "key": "v-9ae58c02",
      "path": "/en/nginx/",
      "headers": [
        {
          "level": 2,
          "title": "1.nginx的proxy_pass配置路径，加与不加“/”差异巨大",
          "slug": "_1-nginx的proxy-pass配置路径，加与不加“-”差异巨大"
        },
        {
          "level": 3,
          "title": "1.1 绝对路径",
          "slug": "_1-1-绝对路径"
        },
        {
          "level": 3,
          "title": "1.2 相对路径",
          "slug": "_1-2-相对路径"
        },
        {
          "level": 3,
          "title": "1.3 代理路径添加uri",
          "slug": "_1-3-代理路径添加uri"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/en/nginx/config/",
      "relativePath": "en/nginx/config/README.md",
      "key": "v-f9e97bc0",
      "path": "/en/nginx/config/"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/avatar-upload.html",
      "relativePath": "features/components/avatar-upload.md",
      "key": "v-c7d6cf9c",
      "path": "/features/components/avatar-upload.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/back-to-top.html",
      "relativePath": "features/components/back-to-top.md",
      "key": "v-0c7dbb9c",
      "path": "/features/components/back-to-top.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/breadcrumb.html",
      "relativePath": "features/components/breadcrumb.md",
      "key": "v-b7d0266c",
      "path": "/features/components/breadcrumb.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/charts.html",
      "relativePath": "features/components/charts.md",
      "key": "v-9b0e17b4",
      "path": "/features/components/charts.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/draggable-kanban.html",
      "relativePath": "features/components/draggable-kanban.md",
      "key": "v-9b6e443c",
      "path": "/features/components/draggable-kanban.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/draggable-list.html",
      "relativePath": "features/components/draggable-list.md",
      "key": "v-769cbb14",
      "path": "/features/components/draggable-list.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/draggable-menu.html",
      "relativePath": "features/components/draggable-menu.md",
      "key": "v-9c1298dc",
      "path": "/features/components/draggable-menu.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/draggable-select.html",
      "relativePath": "features/components/draggable-select.md",
      "key": "v-fa737cd0",
      "path": "/features/components/draggable-select.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/dropzone.html",
      "relativePath": "features/components/dropzone.md",
      "key": "v-f45c38cc",
      "path": "/features/components/dropzone.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/github-corner.html",
      "relativePath": "features/components/github-corner.md",
      "key": "v-2faa5c1c",
      "path": "/features/components/github-corner.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/error-log.html",
      "relativePath": "features/components/error-log.md",
      "key": "v-396331f2",
      "path": "/features/components/error-log.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/hamburger.html",
      "relativePath": "features/components/hamburger.md",
      "key": "v-6f0610b2",
      "path": "/features/components/hamburger.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/header-search.html",
      "relativePath": "features/components/header-search.md",
      "key": "v-33d27852",
      "path": "/features/components/header-search.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/json-editor.html",
      "relativePath": "features/components/json-editor.md",
      "key": "v-4c6a8ad2",
      "path": "/features/components/json-editor.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/lang-select.html",
      "relativePath": "features/components/lang-select.md",
      "key": "v-2537791c",
      "path": "/features/components/lang-select.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/markdown-editor.html",
      "relativePath": "features/components/markdown-editor.md",
      "key": "v-75154f72",
      "path": "/features/components/markdown-editor.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/material-input.html",
      "relativePath": "features/components/material-input.md",
      "key": "v-222a2188",
      "path": "/features/components/material-input.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/pagination.html",
      "relativePath": "features/components/pagination.md",
      "key": "v-582b381c",
      "path": "/features/components/pagination.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/pan-thumb.html",
      "relativePath": "features/components/pan-thumb.md",
      "key": "v-790de5dc",
      "path": "/features/components/pan-thumb.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/right-panel.html",
      "relativePath": "features/components/right-panel.md",
      "key": "v-dc84bb1c",
      "path": "/features/components/right-panel.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/rich-editor.html",
      "relativePath": "features/components/rich-editor.md",
      "key": "v-0115b35c",
      "path": "/features/components/rich-editor.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/screenfull.html",
      "relativePath": "features/components/screenfull.md",
      "key": "v-20b3e6da",
      "path": "/features/components/screenfull.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/size-select.html",
      "relativePath": "features/components/size-select.md",
      "key": "v-e4d5fadc",
      "path": "/features/components/size-select.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/theme-picker.html",
      "relativePath": "features/components/theme-picker.md",
      "key": "v-44c909ec",
      "path": "/features/components/theme-picker.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/sticky.html",
      "relativePath": "features/components/sticky.md",
      "key": "v-ab08a604",
      "path": "/features/components/sticky.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/text-hover-effect.html",
      "relativePath": "features/components/text-hover-effect.md",
      "key": "v-3b819adc",
      "path": "/features/components/text-hover-effect.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/upload-excel.html",
      "relativePath": "features/components/upload-excel.md",
      "key": "v-6b67f80c",
      "path": "/features/components/upload-excel.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/components/upload-image.html",
      "relativePath": "features/components/upload-image.md",
      "key": "v-1c74a5b2",
      "path": "/features/components/upload-image.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/directives/draggable-dialog.html",
      "relativePath": "features/directives/draggable-dialog.md",
      "key": "v-214876dc",
      "path": "/features/directives/draggable-dialog.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/directives/clipboard.html",
      "relativePath": "features/directives/clipboard.md",
      "key": "v-1798bd5c",
      "path": "/features/directives/clipboard.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/directives/permission.html",
      "relativePath": "features/directives/permission.md",
      "key": "v-e78344e4",
      "path": "/features/directives/permission.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/features/icons/svg-icons.html",
      "relativePath": "features/icons/svg-icons.md",
      "key": "v-af4635f8",
      "path": "/features/icons/svg-icons.html"
    },
    {
      "title": "npm",
      "frontmatter": {},
      "regularPath": "/npm&yarn/",
      "relativePath": "npm&yarn/README.md",
      "key": "v-25d06128",
      "path": "/npm&yarn/",
      "headers": [
        {
          "level": 2,
          "title": "全局安装 nrm",
          "slug": "全局安装-nrm"
        },
        {
          "level": 2,
          "title": "查看当前可使用的镜像源",
          "slug": "查看当前可使用的镜像源"
        },
        {
          "level": 2,
          "title": "使用镜像源进行依赖下载",
          "slug": "使用镜像源进行依赖下载"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/features/pwa/service-worker-update-popup.html",
      "relativePath": "features/pwa/service-worker-update-popup.md",
      "key": "v-16454b68",
      "path": "/features/pwa/service-worker-update-popup.html"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/powerplatform/",
      "relativePath": "powerplatform/README.md",
      "key": "v-b24faef8",
      "path": "/powerplatform/"
    },
    {
      "title": "PCF控件",
      "frontmatter": {},
      "regularPath": "/powerplatform/powerapps/code.html",
      "relativePath": "powerplatform/powerapps/code.md",
      "key": "v-1f73df28",
      "path": "/powerplatform/powerapps/code.html",
      "headers": [
        {
          "level": 2,
          "title": "创建",
          "slug": "创建"
        },
        {
          "level": 2,
          "title": "更新",
          "slug": "更新"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/features/directives/waves.html",
      "relativePath": "features/directives/waves.md",
      "key": "v-45589d52",
      "path": "/features/directives/waves.html"
    },
    {
      "title": "界面操作",
      "frontmatter": {},
      "regularPath": "/powerplatform/powerapps/view.html",
      "relativePath": "powerplatform/powerapps/view.md",
      "key": "v-489f8608",
      "path": "/powerplatform/powerapps/view.html",
      "headers": [
        {
          "level": 2,
          "title": "sftp",
          "slug": "sftp"
        }
      ]
    },
    {
      "title": "1.nginx的proxy_pass配置路径，加与不加“/”差异巨大",
      "frontmatter": {},
      "regularPath": "/nginx/",
      "relativePath": "nginx/README.md",
      "key": "v-eb92f680",
      "path": "/nginx/",
      "headers": [
        {
          "level": 2,
          "title": "1.nginx的proxy_pass配置路径，加与不加“/”差异巨大",
          "slug": "_1-nginx的proxy-pass配置路径，加与不加“-”差异巨大"
        },
        {
          "level": 3,
          "title": "1.1 绝对路径",
          "slug": "_1-1-绝对路径"
        },
        {
          "level": 3,
          "title": "1.2 相对路径",
          "slug": "_1-2-相对路径"
        },
        {
          "level": 3,
          "title": "1.3 代理路径添加uri",
          "slug": "_1-3-代理路径添加uri"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/nginx/config/",
      "relativePath": "nginx/config/README.md",
      "key": "v-b38ec94e",
      "path": "/nginx/config/"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "locales": {
      "/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "nav": [
          {
            "text": "D365 CRM 文档",
            "link": "/CRM/"
          },
          {
            "text": "Power Platform",
            "link": "/powerplatform/"
          },
          {
            "text": "生态系统",
            "items": [
              {
                "text-en": "Repositories",
                "text-zh": "项目",
                "items": [
                  {
                    "text-en": "vue-typescript-admin",
                    "text-zh": "vue-element-admin管理",
                    "link": "https://github.com/Armour/vue-typescript-admin-template",
                    "text": "vue-element-admin管理"
                  }
                ],
                "text": "项目"
              },
              {
                "text-en": "Help",
                "text-zh": "帮助",
                "items": [
                  {
                    "text-en": "FAQ",
                    "text-zh": "常见问题",
                    "link": "/guide/other/faq",
                    "text": "常见问题"
                  },
                  {
                    "text-en": "Wechat Group",
                    "text-zh": "微信群",
                    "link": "https://github.com/Armour/vue-typescript-admin-template/issues/62",
                    "text": "微信群"
                  }
                ],
                "text": "帮助"
              }
            ]
          }
        ],
        "sidebar": {
          "/CRM/": [
            {
              "title": "发布",
              "children": [
                "/CRM/publish/operation"
              ]
            },
            {
              "title": "代码",
              "children": [
                "/CRM/code/qianduan",
                "/CRM/code/houtai"
              ]
            }
          ],
          "/powerplatform/": [
            {
              "title": "发布",
              "children": [
                "/powerplatform/powerapps/code",
                "/powerplatform/powerapps/view"
              ]
            }
          ]
        }
      },
      "/en/": {
        "selectText": "Languages",
        "label": "English",
        "nav": [
          {
            "text": "D365 CRM Document",
            "link": "/en/CRM/"
          },
          {
            "text": "Power Platform",
            "link": "/en/powerplatform/"
          },
          {
            "text": "Ecosystem",
            "items": [
              {
                "text-en": "Repositories",
                "text-zh": "项目",
                "items": [
                  {
                    "text-en": "vue-typescript-admin",
                    "text-zh": "vue-element-admin管理",
                    "link": "https://github.com/Armour/vue-typescript-admin-template",
                    "text": "vue-typescript-admin"
                  }
                ],
                "text": "Repositories"
              },
              {
                "text-en": "Help",
                "text-zh": "帮助",
                "items": [
                  {
                    "text-en": "FAQ",
                    "text-zh": "常见问题",
                    "link": "/en/guide/other/faq",
                    "text": "FAQ"
                  },
                  {
                    "text-en": "Wechat Group",
                    "text-zh": "微信群",
                    "link": "https://github.com/Armour/vue-typescript-admin-template/issues/62",
                    "text": "Wechat Group"
                  }
                ],
                "text": "Help"
              }
            ]
          }
        ],
        "sidebar": {
          "/en/CRM/": [
            {
              "title": "publish",
              "children": [
                "/en/CRM/publish/operation"
              ]
            },
            {
              "title": "code",
              "children": [
                "/en/CRM/code/qianduan",
                "/en/CRM/code/houtai"
              ]
            }
          ],
          "/en/powerplatform/": [
            {
              "title": "Power Apps",
              "children": [
                "/en/powerplatform/powerapps/code",
                "/en/powerplatform/powerapps/view"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "path": "/"
    },
    "/en/": {
      "lang": "zh-CN",
      "path": "/en/"
    }
  }
}